CREATE TABLE Test (
  PKey INT PRIMARY KEY,
  A NVARCHAR(50),
  B DATE CONSTRAINT Ls NOT NULL,
  C INT
)

ALTER TABLE Test DROP COLUMN A

ALTER TABLE Test ADD CONSTRAINT FKey FOREIGN KEY(C) REFERENCES TestB(X) ON DELETE NO ACTION ON UPDATE CASCADE

ALTER TABLE Test DROP CONSTRAINT Ls

ALTER TABLE Test ADD D INT NULL